//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_TablePicker
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MD_Object
    {
        public int DatabaseId { get; set; }
        public int SubjectAreaID { get; set; }
        public int ObjectID { get; set; }
        public string ObjectDisplayName { get; set; }
        public string ObjectSchemaName { get; set; }
        public string ObjectPhysicalName { get; set; }
        public string ObjectPKField { get; set; }
        public string ObjectType { get; set; }
        public string ObjectPurpose { get; set; }
        public string ObjectShortDescription { get; set; }
        public string ObjectLongDescription { get; set; }
        public string ObjectUsageTips { get; set; }
        public string ObjectStewardContact { get; set; }
        public Nullable<System.DateTime> LastRefreshDate { get; set; }
        public string UpdateFrequency { get; set; }
        public string ObjectOutputLocation { get; set; }
        public string ObjectOutputRecipients { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDT { get; set; }
        public Nullable<int> KeyDateObjectAttributeID { get; set; }
        public Nullable<bool> IsObjectInDB { get; set; }
    
        public virtual MD_Database MD_Database { get; set; }
    }
}
