//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_TablePicker
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MD_Database
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_Database()
        {
            this.MD_Object = new ObservableCollection<MD_Object>();
        }
    
        public int DatabaseId { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseShortDescription { get; set; }
        public string DatabaseLongDescription { get; set; }
        public string DatabaseType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<MD_Object> MD_Object { get; set; }
    }
}
