USE master
GO


IF DB_ID('AutoTest') IS NOT NULL
BEGIN
	RAISERROR('DROP DATABASE',1,1) WITH NOWAIT;
	ALTER DATABASE AutoTest 
	SET SINGLE_USER 
	WITH ROLLBACK IMMEDIATE;
	DROP DATABASE AutoTest;
END
GO

IF DB_ID('AutoTest') IS NULL
BEGIN
	RAISERROR('CREATE DATABASE',1,1) WITH NOWAIT;
	CREATE DATABASE AutoTest;
END
GO

USE AutoTest
GO